# Tolerances
pattern_tolerance_ms: 20
segment_tolerance_ms: 10

# Overall weighting of pattern difficutlties in get_pattern_weighting
get_pattern_weighting_top_percentage: 0.4
get_pattern_weighting_top_weight: 0.9
get_pattern_weighting_bottom_weight: 0.1

# Density Average
sample_window_secs: 1 # Default 1
moving_avg_window: 5 # Default 5

# Interval NPS Thresholds
short_interval_nps: 5 # Default 5
med_interval_nps: 1 # Default 1
long_interval_nps: 0.5 # Default 0.5

#### Pattern Class Attributes
default_variation_weighting: 0.5
default_pattern_weighting: 0.5
short_int_debuff: 0.7
med_int_debuff: 0.6
long_int_debuff: 0.4
extra_int_end_debuff: 0.9 # For if the interval is at the start or end

#### Strategies
# OtherCalcPatternMultiplier
other_switch_multiplier: 1
other_short_int_multiplier: 0.8
other_med_int_multiplier: 0.7
other_long_int_multiplier: 0.5

#### Defined Pattern Multipliers
# nothing_but_theory
nothing_but_theory_low_bound: 1
nothing_but_theory_up_bound: 2
nothing_but_theory_low_clamp: 2.5
nothing_but_theory_up_clamp: 21.5

# varying_streams
varying_streams_low_bound: 1
varying_streams_up_bound: 2
varying_streams_low_clamp: 2.5
varying_streams_up_clamp: 20.5

# zig_zag_multiplier
zig_zag_low_bound: 1
zig_zag_up_bound: 2
zig_zag_low_clamp: 6
zig_zag_up_clamp: 18

# even_circle_multiplier
even_circle_low_bound: 1
even_circle_up_bound: 1.55

# skewed_circle_multiplier
skewed_circle_low_bound: 1
skewed_circle_up_bound: 1.75

# stream_multiplier
stream_low_bound: 1
stream_up_bound: 1.3
stream_low_clamp: 6.5
stream_up_clamp: 12

# pattern_stream_length_multiplier
pattern_stream_length_low_bound: 1.025
pattern_stream_length_up_bound: 1.1
pattern_stream_length_low_clamp: 6.5
pattern_stream_length_up_clamp: 20

# zig_zag_length_multiplier
zig_zag_length_low_bound: 1.0
zig_zag_length_up_bound: 1.2
zig_zag_length_low_clamp: 10
zig_zag_length_up_clamp: 30

# four_stack_multiplier
four_stack_low_bound: 1.0
four_stack_up_bound: 1.4
four_stack_low_clamp: 6
four_stack_up_clamp: 12

# three_stack_multiplier
three_stack_low_bound: 1.0
three_stack_up_bound: 1.25
three_stack_low_clamp: 6
three_stack_up_clamp: 12

# two_stack_multiplier
two_stack_low_bound: 1.0
two_stack_up_bound: 1.20
two_stack_low_clamp: 6
two_stack_up_clamp: 12

# varying_stacks_multiplier
varying_stacks_low_bound: 1.0
varying_stacks_up_bound: 1.35
varying_stacks_low_clamp: 4
varying_stacks_up_clamp: 14
